### ISSUE TITLE
AttributeError: 'GeneralTracker' object has no attribute 'run'

### ISSUE THREAD

**Issue by KhoiDOO** [KhoiDOO/seglord#1]
```
Total number of Params: 14329972
Total number of Params: 14329972
Device in use: cuda:0
Device in use: cuda:1
wandb: Currently logged in as: khoido8899 (truelove). Use `wandb login --relogin` to force relogin
wandb: Tracking run with wandb version 0.17.0
wandb: Run data is saved locally in /media/mountHDD2/git/seglord/seglord/wandb/run-20240527_214257-kmam313l
wandb: Run `wandb offline` to turn off syncing.
wandb: Syncing run 05_27_2024_21_42_56
wandb: ⭐️ View project at https://wandb.ai/truelove/seglord
wandb: 🚀 View run at https://wandb.ai/truelove/seglord/runs/kmam313l
Epoch: 0 - train/loss: 0.93 - train/miou: 0.03 - train/dice: 0.00 - valid/loss: 1.02 - valid/miou: 0.02 - valid/dice: 0.00: 100%|█████████████████████████████████████████████| 1/1 [01:30<00:00, 90.95s/it]
[rank1]: Traceback (most recent call last):
[rank1]:   File "/media/mountHDD2/git/seglord/seglord/main.py", line 147, in <module>
[rank1]:     main()
[rank1]:   File "/media/mountHDD2/git/seglord/seglord/main.py", line 142, in main
[rank1]:     evaluator.sync(accelerator=accelerator)
[rank1]:   File "/media/mountHDD2/git/seglord/seglord/metrics/eval.py", line 208, in sync
[rank1]:     wandb_tracker.run.log_artifact(best_model_art)
[rank1]: AttributeError: 'GeneralTracker' object has no attribute 'run'
W0527 21:44:32.935000 140080319242752 torch/distributed/elastic/multiprocessing/api.py:851] Sending process 1377426 closing signal SIGTERM
E0527 21:44:33.149000 140080319242752 torch/distributed/elastic/multiprocessing/api.py:826] failed (exitcode: 1) local_rank: 1 (pid: 1377427) of binary: /media/mountHDD2/git/seglord/.env/bin/python
Traceback (most recent call last):
  File "/media/mountHDD2/git/seglord/.env/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/media/mountHDD2/git/seglord/.env/lib/python3.10/site-packages/accelerate/commands/accelerate_cli.py", line 46, in main
    args.func(args)
  File "/media/mountHDD2/git/seglord/.env/lib/python3.10/site-packages/accelerate/commands/launch.py", line 1073, in launch_command
    multi_gpu_launcher(args)
  File "/media/mountHDD2/git/seglord/.env/lib/python3.10/site-packages/accelerate/commands/launch.py", line 718, in multi_gpu_launcher
    distrib_run.run(args)
  File "/media/mountHDD2/git/seglord/.env/lib/python3.10/site-packages/torch/distributed/run.py", line 870, in run
    elastic_launch(
  File "/media/mountHDD2/git/seglord/.env/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 132, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/media/mountHDD2/git/seglord/.env/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 263, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
main.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-05-27_21:44:32
  host      : exx-desktop
  rank      : 1 (local_rank: 1)
  exitcode  : 1 (pid: 1377427)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
```

**Comment by KhoiDOO** [comment]
This problem occurred when conducting the experiment with multi-gpus

**Comment by KhoiDOO** [comment]
Fixed
